package org.telegram.messenger.leemen;

import android.os.Build;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;

import org.telegram.messenger.FileLog;

import java.security.KeyStore;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * At-rest protection for the raw 32-byte K_master before it goes into SharedPreferences.
 *
 * We can't store K_master AS a Keystore key (we need the raw bytes to feed XChaCha20 in the sync phase),
 * so we envelope-encrypt it: a non-exportable AES-256-GCM key lives in the AndroidKeyStore (TEE-backed),
 * and we keep only the wrapped blob. NOT biometric-gated (setUserAuthenticationRequired) on purpose —
 * background blob-sync must decrypt K_master with no user present.
 *
 * minSdk is 21; AndroidKeyStore symmetric keys require API 23 (KeyGenParameterSpec). On API 21–22 we fall
 * back to storing K_master plaintext-b64 (prefixed "p0:"). That is acceptable: per «Общая инфо» the local
 * PS data is already readable by anyone with device access, so the only thing K_master protects is the
 * server blob (E2E), and the Keystore path covers the vast majority of devices.
 */
public final class LeemenKeyStore {

    private LeemenKeyStore() {}

    private static final String ANDROID_KEYSTORE = "AndroidKeyStore";
    private static final String WRAP_KEY_ALIAS = "leemen_master_wrap_v1";
    private static final int GCM_IV_LEN = 12;
    private static final int GCM_TAG_BITS = 128;

    private static final String PREFIX_KEYSTORE = "k1:"; // AES/GCM via AndroidKeyStore
    private static final String PREFIX_PLAIN = "p0:";    // API < 23 fallback

    /** Wrap raw bytes for storage. Returns a self-describing string (prefix + b64), never null on success. */
    public static String protect(byte[] plain) {
        if (plain == null) return null;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            try {
                SecretKey key = getOrCreateWrapKey();
                Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
                cipher.init(Cipher.ENCRYPT_MODE, key);
                byte[] iv = cipher.getIV(); // 12 bytes, generated by the provider
                byte[] ct = cipher.doFinal(plain);
                byte[] out = new byte[iv.length + ct.length];
                System.arraycopy(iv, 0, out, 0, iv.length);
                System.arraycopy(ct, 0, out, iv.length, ct.length);
                return PREFIX_KEYSTORE + Base64.encodeToString(out, Base64.NO_WRAP);
            } catch (Throwable e) {
                FileLog.e(e); // fall through to plaintext fallback
            }
        }
        return PREFIX_PLAIN + Base64.encodeToString(plain, Base64.NO_WRAP);
    }

    /** Reverse of {@link #protect}. Returns null if the blob can't be recovered. */
    public static byte[] unprotect(String stored) {
        if (stored == null) return null;
        try {
            if (stored.startsWith(PREFIX_PLAIN)) {
                return Base64.decode(stored.substring(PREFIX_PLAIN.length()), Base64.NO_WRAP);
            }
            if (stored.startsWith(PREFIX_KEYSTORE)) {
                byte[] blob = Base64.decode(stored.substring(PREFIX_KEYSTORE.length()), Base64.NO_WRAP);
                if (blob.length <= GCM_IV_LEN) return null;
                byte[] iv = new byte[GCM_IV_LEN];
                byte[] ct = new byte[blob.length - GCM_IV_LEN];
                System.arraycopy(blob, 0, iv, 0, GCM_IV_LEN);
                System.arraycopy(blob, GCM_IV_LEN, ct, 0, ct.length);
                SecretKey key = getOrCreateWrapKey();
                Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
                cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(GCM_TAG_BITS, iv));
                return cipher.doFinal(ct);
            }
        } catch (Throwable e) {
            FileLog.e(e);
        }
        return null;
    }

    private static SecretKey getOrCreateWrapKey() throws Exception {
        KeyStore ks = KeyStore.getInstance(ANDROID_KEYSTORE);
        ks.load(null);
        if (ks.containsAlias(WRAP_KEY_ALIAS)) {
            KeyStore.SecretKeyEntry entry = (KeyStore.SecretKeyEntry) ks.getEntry(WRAP_KEY_ALIAS, null);
            return entry.getSecretKey();
        }
        KeyGenerator kg = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE);
        kg.init(new KeyGenParameterSpec.Builder(WRAP_KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build());
        return kg.generateKey();
    }
}
